#!/bin/bash

export DEFAULT_MYSQL_HOST=${DEFAULT_MYSQL_HOST:-localhost}
export DEFAULT_MYSQL_PORT=${DEFAULT_MYSQL_PORT:-3306}
export DEFAULT_MYSQL_USER=${DEFAULT_MYSQL_USER:-icinga2}
export DEFAULT_MYSQL_PASS=${DEFAULT_MYSQL_PASS:-$(pwgen -s 15 1)}

export MYSQL_ROOT_USER=${MYSQL_ROOT_USER:-root}

export ICINGA2_IDO_MYSQL_HOST=${ICINGA2_IDO_MYSQL_HOST:-${DEFAULT_MYSQL_HOST}}
export ICINGA2_IDO_MYSQL_PORT=${ICINGA2_IDO_MYSQL_PORT:-${DEFAULT_MYSQL_PORT}}
export ICINGA2_IDO_MYSQL_USER=${ICINGA2_IDO_MYSQL_USER:-${DEFAULT_MYSQL_USER}}
export ICINGA2_IDO_MYSQL_PASS=${ICINGA2_IDO_MYSQL_PASS:-${IDO_PASSWORD:-${DEFAULT_MYSQL_PASS}}}
export ICINGA2_IDO_MYSQL_DATA=${ICINGA2_IDO_MYSQL_DATA:-icinga2idomysql}


locale-gen &

run-parts --lsbsysinit --exit-on-error -- /opt/setup

cat <<-END
Starting Supervisor.
END

icinga2 daemon --validate

/usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n &
trap "supervisorctl shutdown && wait" SIGTERM
wait
