#!/bin/bash

locale-gen &

run-parts --lsbsysinit --exit-on-error -- /opt/setup

cat <<-END
Starting Supervisor.
END

icinga2 daemon --validate

/usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n &
trap "supervisorctl shutdown && wait" SIGTERM
wait
